# Generated by Django 4.2.7 on 2023-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('miles', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
            ],
        ),
    ]
