# Generated by Django 4.2.7 on 2023-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
